version: "3"
services:
  app:
    image: 'todo-list'
    container_name: 'todo-list'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT:-3100}:${PORT:-3100}