export const CREATE_USER = 'user/createUser'
export const DELETE_TASK = 'tasks/deleteTask'
export const RESOLVE_TASK = 'tasks/resolveTask'
export const GET_TASKS = 'tasks/getTasks'
export const CREATE_TASK = 'tasks/createTask'
export const HIDE_INPUT = 'updateInputs/hideInput'
export const UPDATE_TASK = 'tasks/updateTask'